import streamlit as st
st.title('streamlit demo')
st.header('this is Header')
st.subheader('this is SUBHEADER')
st.markdown('---------------')
st.success('This is green')
st.error('this is red')
st.info(' this is blue')
st.warning('this is yellow')
st.markdown('------------------')